version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      DB_HOST: DB_HOST
      DB_USER: DB_USER
      DB_PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME
